# Generated by Django 4.0.3 on 2022-03-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_time_eventslot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eventapp.event'),
            preserve_default=False,
        ),
    ]
